n1 = int(input("Informe um número: "))
n2 = int(input("Informe outro número: "))
n3 = int(input("Informe outro número: "))
soma = ( n1*n1) + (n2*n2) + (n3*n3)
print(f"A soma do quadrado dos valores: {n1}, {n2} e {n3} é: {soma}")
